[NEAT]
fitness_critetion = max
fitness_threshold = 0.94
pop_size = 20
reset_on_extinction = False

# ----------------------------------------
[TensorGenome]
activation_default = relu
activation_mutation_rate = 0.4
activation_options = sigmoid tanh

# The mean of the normal/gaussian distribution
bias_init_mean = 0.0
bias_init_stdev = 1.0
bias_max_value = 40
bias_min_value = -40
# The standard deviation of the zero-centered normal/gaussian distribution 
# from which a bias value mutation is drawn.
bias_mutate_power = 0.3
bias_mutate_rate = 0.2

# The probability that mutation will replace the bias of a node with a newly 
# chosen random value (as if it were a new node).
bias_replace_rate = 0.1

# ----------------------------------------
# The coefficient for the disjoint and excess gene counts’ 
# contribution to the genomic distance.
compatibility_disjoint_coefficient = 1.0

# The coefficient for each weight, bias, or response multiplier difference’s 
# contribution to the genomic distance (for homologous nodes or connections)
compatibility_weight_coefficient = 0.7
# ----------------------------------------

conn_add_prob = 0.7
conn_delete_prob = 0.2
enabled_default = True

# The probability that mutation will replace (50/50 chance of True or False) 
# the enabled status of a connection. Valid values are in [0.0, 1.0].
enabled_mutate_rate = 0.2

feed_forward = True
initial_connection = full_nodirect

node_add_prob = 0.7
node_delete_prob = 0.2

num_hidden = 0
num_inputs = 2
num_outputs = 2


# ----------------------------------------
[DefaultSpeciesSet]
# Individuals whose genomic distance is less than this threshold 
# are considered to be in the same species.
compatibility_threshold = 3.0



# ----------------------------------------
[DefaultStagnation]
species_fitness_func = max
# Species that have not shown improvement in more than this number 
# of generations will be considered stagnant and removed.
max_stagnation = 4

# The number of species that will be protected from stagnation; 
# mainly intended to prevent total extinctions caused by all species becoming stagnant before new species arise.
species_elitism = 1 

# ----------------------------------------
[DefaultReproduction]
# The number of most-fit individuals in each species that will be preserved 
# as-is from one generation to the next.
elitism = 2

# The fraction for each species allowed to reproduce each generation
survival_threshold = 0.4
